Refactor DrivvoOptionsFlowHandler initialization
Fix deprecated OptionsFlow causing error in HA Core 2025.12+:
AttributeError: property 'config_entry' of 'DrivvoOptionsFlowHandler' object has no setter

Removed manual config_entry assignment as backwards compatibility was removed in HA Core 2025.12.

https://developers.home-assistant.io/blog/2024/11/12/options-flow/